### PR TITLE
Add formatting check, and format all files

### PR DESCRIPTION
**Pull request by fig02**
This adds a formatting check to github actions. If any misformatted files are found, the workflow checks stop and a red X will show on `Build All / Check Formatting`.

A bunch of files get touched in this PR because the formatted hasn't been run for a long time it seems.

### CODE REVIEW

**Comment by fig02** [comment]
This is ready to review/merge.

I would strongly recommend selecting "squash and merge" when merging this PR, so that all of my individual test commits do not show up in the commit history. It will condense all of my work down into one commit when merging it into main.

image

**Comment by fig02** [comment]
There are alot of changes in here from the formatter that may not be desirable-- These can be tweaked by changing the .clang-format settings to everyones liking

**Comment by fig02** [comment]
We also may want to update clang-format to something newer than version 10. 
oot decomp uses clang-format-14 which allows `AllowShortEnumsOnASingleLine: false`, which would prevent this from happening
image

**Review by EJ125 — COMMENTED** [review]
looks good, taka approved as well

**Review by EJ125 — APPROVED** [review]

**Pull request merged**
